#!/bin/sh
set -e

case "$1" in
    configure)

    if ! getent passwd geth-exporter >/dev/null; then
        adduser --system \
                --home /run/geth-exporter --no-create-home \
                geth-exporter
    fi
    ;;
esac

#DEBHELPER#
